=== alejandroatacho/Python-XML-parser/views/sample.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="country" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="rank" type="xs:string" />
                            <xs:element name="year" type="xs:string" />
                            <xs:element name="gdppc" type="xs:string" />
                            <xs:element name="neighbor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="name" use="required" />
                                    <xs:attribute name="direction" use="required" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" use="required" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="data" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== alejandroatacho/Python-XML-parser/views/sample.xml
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sample.xsd">
    <country name="USA">
        <rank>1</rank>
        <year>2008</year>
        <gdppc>141100</gdppc>
        <neighbor name="Austria" direction="E" />
        <neighbor name="Switzerland" direction="W" />
    </country>
    <country name="Singapore">
        <rank>4</rank>
        <year>2011</year>
        <gdppc>59900</gdppc>
        <neighbor name="Malaysia" direction="N" />
    </country>
    <country name="Panama">
        <rank>68</rank>
        <year>2011</year>
        <gdppc>13600</gdppc>
        <neighbor name="Costa Rica" direction="W" />
        <neighbor name="Colombia" direction="E" />
    </country>
    <data />
</data>
